<a href="https://colab.research.google.com/github/Arslonbekjon/ML-Amaliyot-Tashkent-uy-narxlari/blob/main/Tashkent_uy_narxlari_machine_learning_qismi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
URL = "https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv"
df = pd.read_csv(URL)

In [7]:
dfp = df[df['price']=="Договорная"].index
df.drop(dfp,inplace=True)
df['price'] = df['price'].astype(float)

dfs = df[df['size']=="Площадьземли:1сот"].index
df.drop(dfs,inplace=True)
df['size'] = df['size'].astype(float)


dfss = df[df['size']>160].index
df.drop(dfss,inplace=True)

dfpr = df[df['price']>1000000].index
df.drop(dfpr,inplace=True)

df.drop('location',axis=1,inplace=True)

In [8]:

from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2,random_state=42)

X_train = train_set.drop('price',axis=1)
y = train_set['price'].copy()

X_num = X_train.drop('district', axis=1)

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_pipeline = Pipeline([
    ('std_scaler', StandardScaler())
])

In [10]:
from sklearn.compose import ColumnTransformer

num_attribs = list(X_num)
categ_attribs = ['district']

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),
    ('categ',OneHotEncoder(),categ_attribs)
])

In [11]:
X_prepared= full_pipeline.fit_transform(X_train)

In [12]:
X_prepared

array([[-0.55016038, -0.64393601, -1.21002598, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.45060261,  1.76619349, -1.21002598, ...,  0.        ,
         0.        ,  0.        ],
       [-0.55016038, -0.56618989, -0.30718443, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.55016038,  0.05577901,  0.14423634, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.45060261, -0.48844378,  0.59565712, ...,  0.        ,
         0.        ,  0.        ],
       [-0.55016038, -0.72168212,  0.14423634, ...,  0.        ,
         0.        ,  0.        ]])

In [13]:
###Linear Regression

In [14]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()


In [15]:
LR_model.fit(X_prepared,y)

LinearRegression()

In [16]:
test_data = X_train.sample(10)
test_data

district  rooms   size  level  max_levels
6078        Мирабадский      4  104.0      8           9
6821  Мирзо-Улугбекский      3   75.0      3           4
840         Учтепинский      2   63.0      2           5
7074  Мирзо-Улугбекский      3   85.0      8           9
3402  Мирзо-Улугбекский      3   68.0      3           4
5274        Яшнободский      2   51.0      2           9
4664        Яшнободский      2   55.0      2           5
158        Сергелийский      2   54.0      6           7
3442        Олмазорский      5  110.0      5           5
1389        Учтепинский      4   78.0      3           4

In [17]:
test_label = y.loc[test_data.index]
test_label

6078    94000.0
6821    90000.0
840     42000.0
7074    58000.0
3402    40000.0
5274    42000.0
4664    30800.0
158     36000.0
3442    63500.0
1389    53500.0
Name: price, dtype: float64

In [19]:
test_data_prepared = full_pipeline.transform(test_data)
test_data_prepared

array([[ 1.45136561,  1.37746293,  1.94991944,  1.15478084,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.45060261,  0.25014429, -0.30718443, -0.76554229,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.55016038, -0.21633239, -0.7586052 , -0.38147766,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.45060261,  0.63887486,  1.94991944,  1.15478084,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.45060261, -0.0219671 , -0

In [20]:
predicted_labels = LR_model.predict(test_data_prepared)

In [21]:
predicted_labels

array([91461.07367727, 58976.87248575, 48232.62775333, 63919.5281805 ,
       51379.85635628, 38529.11548783, 40455.55348848, 22038.11403473,
       73235.44670742, 50864.83161009])

In [22]:
pd.DataFrame({"Bashorat":predicted_labels,"Asl qiymat":test_label})

Bashorat  Asl qiymat
6078  91461.073677     94000.0
6821  58976.872486     90000.0
840   48232.627753     42000.0
7074  63919.528181     58000.0
3402  51379.856356     40000.0
5274  38529.115488     42000.0
4664  40455.553488     30800.0
158   22038.114035     36000.0
3442  73235.446707     63500.0
1389  50864.831610     53500.0

In [24]:
X_test = test_set.drop('price',axis=1)
X_test

district  rooms   size  level  max_levels
527       Яккасарайский      2   86.0      6           8
1975      Яккасарайский      2   64.0      1           5
1304        Мирабадский      3  130.0      9          12
1887  Мирзо-Улугбекский      2   50.0      1           4
2668       Чиланзарский      2   54.0      1           4
...                 ...    ...    ...    ...         ...
3793      Яккасарайский      2   48.0      5           9
2040  Мирзо-Улугбекский      3  126.0      5           6
899        Юнусабадский      4   83.0      4           4
6125        Мирабадский      4  147.0      3          12
6402       Чиланзарский      4  105.0      9           9

[1448 rows x 5 columns]

In [25]:
y_test = test_set['price'].copy()
y_test

527      75000.0
1975     42000.0
1304     90000.0
1887     30000.0
2668     34000.0
          ...   
3793     23000.0
2040    141922.0
899      75000.0
6125    132000.0
6402     58000.0
Name: price, Length: 1448, dtype: float64

In [26]:
X_test_prepared = full_pipeline.transform(X_test)

In [30]:
y_predicted = LR_model.predict(X_test_prepared)

In [31]:
y_predicted

array([ 79603.01698709,  62844.26210706, 125332.73153975, ...,
        59596.60793113, 148868.11110941,  77305.1962532 ])

In [32]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_predicted)
print("MAE=",mae)

MAE= 12571.225935001257


In [33]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test,y_predicted)

print("RMSE=",np.sqrt(mse))

RMSE= 20544.661554190698


#Random Forest

In [35]:
from sklearn.ensemble import RandomForestRegressor
RF_model = RandomForestRegressor()
RF_model.fit(X_prepared,y)

RandomForestRegressor()

In [37]:
y_predicted = RF_model.predict(X_test_prepared)

In [38]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_predicted)
print("RMSE=",np.sqrt(mse))

RMSE= 17393.291084938865


#Modelni saqlab olish

In [40]:
import  pickle

filename = "RF_model.pkl"

with open(filename,'wb') as file:
  pickle.dump(RF_model,file)

In [42]:
with open(filename,'rb') as file:
  model = pickle.load(file)

#Joblib usuli

In [43]:
import joblib

filename = "LR_model.jbl"

joblib.dump(RF_model, filename)

['LR_model.jbl']

In [44]:
model = joblib.load(filename)

In [45]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_prepared,y,scoring="neg_mean_squared_error",cv=5)
LR_rmse_scores = np.sqrt(-scores)

def display_scores(scores):
  print("Scores:", scores)
  print("Mean:", scores.mean())
  print("Std.dev:", scores.std())

display_scores(LR_rmse_scores)

Scores: [29954.31292777 20614.39361189 19460.0567923  19373.50860161
 17295.68326816]
Mean: 21339.591040347623
Std.dev: 4438.257850179016
